import type { Location, PrecipRadarData, PrecipRadarMotion, Wrapped } from "@/lib/types";
import { fetchedAtOf, fetchWithTimeout, nowIso, oldestIso } from "@/lib/util";

const ATTRIBUTION = "NOAA MRMS (radar observation)";

/**
 * Where the precomputed radar rain feed lives. The heavy GRIB2 decode +
 * advection work runs OFF Netlify (a GitHub Action writes a small JSON to the
 * `mrms-data` branch, mirroring cloud-data/lightning-data); we just read that
 * tiny file here. Override with MRMS_FEED_URL.
 */
const FEED_URL =
  process.env.MRMS_FEED_URL ??
  "https://raw.githubusercontent.com/jayfrid-bot/bocabeach/mrms-data/mrms_precip.json";

/**
 * How stale the radar FRAME itself may be (its own scan time — NOT when the
 * upstream job ran) before we stop trusting it as "right now".
 *
 * Much tighter than the satellite cloud feed's 45 min (GOES_CLOUD_STALE_MINUTES)
 * because the two answer different questions. Cloud cover is a slowly-varying
 * field where a 40-minute-old read is still roughly true. This feed makes a
 * FALSIFIABLE, short-fuse claim — "rain could reach the beach in ~25 minutes" —
 * and a 25-minute-old frame means that entire prediction window has already
 * elapsed before the user reads it. At a typical 50 km/h storm motion, 25
 * minutes is ~21 km of travel: a third of the whole analysis box. Past that,
 * the honest move is to go quiet rather than narrate where the rain used to be.
 *
 * MRMS itself publishes every 2 minutes, so a stale read here means the
 * publishing Action was throttled (see the cadence note in
 * .github/workflows/mrms.yml), not that the data source gapped.
 */
export const PRECIP_RADAR_STALE_MINUTES = 25;

interface PrecipRadarFeedBeach {
  rainNowMmHr: number | null;
  nearestRainKm: number | null;
  nearestBearingDeg: number | null;
  coveragePct: number | null;
  motion: PrecipRadarMotion | null;
  etaMinutes: number | null;
  frameIso: string | null;
  framesUsed: number;
  note?: string;
}

interface PrecipRadarFeed {
  version?: number;
  generatedAt: string;
  product?: string;
  frames?: string[];
  note?: string;
  beaches: Record<string, PrecipRadarFeedBeach>;
}

/** A finite number or null — the feed is generated by a separate job, so every
 *  numeric field is validated rather than trusted. NaN/Infinity/undefined and
 *  wrong-typed values all normalize to null (unknown), never to 0. */
function num(v: unknown): number | null {
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

function motionOf(v: unknown): PrecipRadarMotion | null {
  if (!v || typeof v !== "object") return null;
  const m = v as Record<string, unknown>;
  const speedKmh = num(m.speedKmh);
  const dirDeg = num(m.dirDeg);
  // A vector needs BOTH components to mean anything — half a vector is not a
  // degraded reading, it's a malformed one.
  if (speedKmh == null || dirDeg == null) return null;
  return {
    speedKmh,
    dirDeg,
    corr: num(m.corr) ?? undefined,
    baselineMin: num(m.baselineMin) ?? undefined,
  };
}

export async function fetchPrecipRadar(loc: Location): Promise<Wrapped<PrecipRadarData>> {
  let fetchedAt = nowIso();
  try {
    const res = await fetchWithTimeout(FEED_URL, {
      timeoutMs: 7000,
      next: { revalidate: 60 }, // the upstream job refreshes on a ~10 min cadence
    });
    fetchedAt = fetchedAtOf(res);
    // The feed branch may not exist yet (first deploy) — degrade quietly.
    if (res.status === 404) {
      return {
        source: ATTRIBUTION,
        status: "best-effort",
        fetchedAt,
        attribution: ATTRIBUTION,
        data: null,
        note: "radar rain feed not published yet",
      };
    }
    if (!res.ok) throw new Error(`mrms precip feed -> ${res.status}`);
    const feed = (await res.json()) as PrecipRadarFeed;
    if (!feed?.beaches || typeof feed.beaches !== "object") {
      throw new Error("malformed mrms precip feed");
    }

    // The GitHub CDN's Date header is serve-time, not generation-time — report
    // the older of the two so RelativeTime matches reality (same as goesCloud.ts).
    fetchedAt = oldestIso(feed.generatedAt, fetchedAtOf(res));

    const b = feed.beaches[loc.slug];
    if (!b) {
      return {
        source: ATTRIBUTION,
        status: "best-effort",
        fetchedAt,
        attribution: ATTRIBUTION,
        data: null,
        note: "beach not in radar feed",
      };
    }

    // Freshness is judged on the RADAR FRAME's own scan time, not on when the
    // job ran — a job that runs every minute republishing an hour-old frame is
    // still an hour-old observation.
    const frameMs = b.frameIso ? Date.parse(b.frameIso) : NaN;
    const frameAgeMinutes = Number.isFinite(frameMs)
      ? Math.max(0, Math.round((Date.now() - frameMs) / 60000))
      : Infinity;
    const stale = !Number.isFinite(frameAgeMinutes) || frameAgeMinutes > PRECIP_RADAR_STALE_MINUTES;

    // No frame at all means the upstream job published its fail-soft nulls
    // (feed down / no frames decoded) — that's an honest "no data", not a
    // reading, so don't hand callers an all-null object to interpret.
    if (!b.frameIso) {
      return {
        source: ATTRIBUTION,
        status: "stale",
        fetchedAt,
        attribution: ATTRIBUTION,
        data: null,
        note: b.note ?? feed.note ?? "no radar frame available",
      };
    }

    const data: PrecipRadarData = {
      rainNowMmHr: num(b.rainNowMmHr),
      nearestRainKm: num(b.nearestRainKm),
      nearestBearingDeg: num(b.nearestBearingDeg),
      coveragePct: num(b.coveragePct),
      motion: motionOf(b.motion),
      etaMinutes: num(b.etaMinutes),
      frameIso: b.frameIso,
      framesUsed: num(b.framesUsed) ?? 0,
      frameAgeMinutes,
    };

    return {
      source: ATTRIBUTION,
      status: stale ? "stale" : "ok",
      fetchedAt,
      attribution: ATTRIBUTION,
      data,
      // Data is still returned when stale — callers decide whether to use it
      // (lib/rainNowcast.ts goes silent; the source list still shows it).
      note: stale
        ? `radar frame is ${frameAgeMinutes} min old`
        : (b.note ?? feed.note ?? undefined),
    };
  } catch (e) {
    return {
      source: ATTRIBUTION,
      status: "error",
      fetchedAt,
      attribution: ATTRIBUTION,
      data: null,
      note: String(e),
    };
  }
}
