// AUTO-GENERATED by scripts/nwps_rip_map.mjs — do not hand-edit.
// Maps each beach slug to the NOAA NWPS office/region whose probabilistic
// rip current model (CG1 ripprob grid) covers it, and the nearest model grid
// point to that beach's shoreline (accepted only when <= 3 km away).
// Regenerate with: node scripts/nwps_rip_map.mjs

export interface NwpsRipCoverage {
  region: string;
  office: string;
  lon: number;
  lat: number;
  distKm: number;
}

export const NWPS_RIP_COVERAGE: Record<string, NwpsRipCoverage> = {
  "asbury-park": { region: "er", office: "phi", lon: -74.015, lat: 40.1665, distKm: 2.06 },
  "boca-raton": { region: "sr", office: "mfl", lon: -80.066, lat: 26.3616, distKm: 0.41 },
  "cape-may": { region: "er", office: "phi", lon: -74.849, lat: 38.952, distKm: 0.83 },
  "cocoa-beach": { region: "sr", office: "mlb", lon: -80.604, lat: 28.3138, distKm: 0.91 },
  "coney-island": { region: "er", office: "okx", lon: -73.979, lat: 40.5688, distKm: 0.43 },
  "daytona-beach": { region: "sr", office: "mlb", lon: -80.996, lat: 29.2113, distKm: 2.6 },
  "deerfield-beach": { region: "sr", office: "mfl", lon: -80.073, lat: 26.3079, distKm: 0.96 },
  "folly-beach": { region: "er", office: "chs", lon: -79.92, lat: 32.6578, distKm: 0.52 },
  "fort-lauderdale": { region: "sr", office: "mfl", lon: -80.101, lat: 26.1136, distKm: 0.7 },
  "galveston": { region: "sr", office: "hgx", lon: -94.746, lat: 29.2992, distKm: 2.19 },
  "gulf-shores": { region: "sr", office: "mob", lon: -87.707, lat: 30.2401, distKm: 0.89 },
  "hammonasset-beach": { region: "er", office: "okx", lon: -72.562, lat: 41.2591, distKm: 0.53 },
  "huntington-beach": { region: "wr", office: "sgx", lon: -118.001, lat: 33.6512, distKm: 0.36 },
  "jacksonville-beach": { region: "sr", office: "jax", lon: -81.394, lat: 30.3814, distKm: 0.98 },
  "la-jolla": { region: "wr", office: "sgx", lon: -117.258, lat: 32.8631, distKm: 0.31 },
  "miami-beach": { region: "sr", office: "mfl", lon: -80.131, lat: 25.7422, distKm: 2.74 },
  "misquamicut": { region: "er", office: "box", lon: -71.808, lat: 41.3145, distKm: 0.83 },
  "montauk": { region: "er", office: "okx", lon: -71.946, lat: 41.0276, distKm: 1.17 },
  "myrtle-beach": { region: "er", office: "ilm", lon: -78.885, lat: 33.6824, distKm: 0.76 },
  "nags-head": { region: "er", office: "mhx", lon: -75.555, lat: 35.8367, distKm: 0.38 },
  "naples": { region: "sr", office: "mfl", lon: -81.818, lat: 26.1293, distKm: 2.63 },
  "old-orchard-beach": { region: "er", office: "gyx", lon: -70.36, lat: 43.5175, distKm: 0.74 },
  "rehoboth-beach": { region: "er", office: "phi", lon: -75.072, lat: 38.7106, distKm: 0.77 },
  "tybee-island": { region: "er", office: "chs", lon: -80.841, lat: 32.0086, distKm: 1.03 },
  "virginia-beach": { region: "er", office: "akq", lon: -75.971, lat: 36.852, distKm: 0.63 },
  "waikiki": { region: "pr", office: "hfo", lon: -157.84, lat: 21.2739, distKm: 0.85 },
  "wrightsville-beach": { region: "er", office: "ilm", lon: -77.786, lat: 34.2113, distKm: 1 },
};
