//
//  BeachBridgeViewController.swift
//  App
//
//  Registers our local (non-npm) Capacitor plugins in code, so registration
//  survives `npx cap sync ios`. capacitor.config.json's `packageClassList`
//  is regenerated by cap sync from npm plugins only — a hand-added local
//  plugin entry there gets silently dropped on the next sync. Registering
//  here in capacitorDidLoad() is the durable fix: this file is only ever
//  touched by us, and cap sync never rewrites it.
//
//  Wired in as the custom class of the bridge view controller in
//  Base.lproj/Main.storyboard, replacing the stock CAPBridgeViewController.
//
import Capacitor

class BeachBridgeViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        bridge?.registerPluginType(BeachSessionActivityPlugin.self)
    }
}
