//
//  BeachSessionActivityPlugin.swift
//  App
//
//  Phase 2 of docs/LIVE_ACTIVITY_PLAN.md — the Capacitor bridge that lets
//  the WebView start/update/end the Beach Session Live Activity and observe
//  its push-token rotations + dismissal. See ios/App/Shared/
//  BeachSessionAttributes.swift for the versioned wire shape and
//  ios/App/App/BeachSessionDemo.swift for the Phase-1 local-only proof this
//  reuses the exact same ActivityKit calls through.
//
//  Registration: this is a LOCAL (non-npm) plugin. `packageClassList` in
//  capacitor.config.json is NOT used — that file is gitignored and gets
//  regenerated by `npx cap sync ios` from npm plugins only, which would
//  silently drop a hand-added local entry. Instead this class is registered
//  in code by BeachBridgeViewController.capacitorDidLoad() (see
//  ios/App/App/BeachBridgeViewController.swift), which is wired in as the
//  bridge view controller's custom class in Base.lproj/Main.storyboard.
//
//  Every method resolves with a structured `{ok, ...}` / `{ok:false,reason}`
//  result and NEVER rejects/throws to JS — a card asking "did this work?"
//  should never have to catch. Every argument from JS is validated before it
//  touches ActivityKit (schema version, slug pattern, finite numbers, score
//  bounds, epoch-ms dates) since it crosses an untrusted JS boundary.
//
//  Origin restriction: calls are only served when the WebView's current URL
//  host is app.isitbeachday.com (release) or localhost (DEBUG) — see
//  `originAllowed`. A WebView that has navigated somewhere else (should never
//  happen with this app's remote-URL config, but this is the same discipline
//  the plan calls for) gets `{ok:false, reason:"origin-not-allowed"}` instead
//  of touching ActivityKit.
//

import Capacitor
import Foundation
import Security
#if canImport(ActivityKit)
import ActivityKit
#endif

@objc(BeachSessionActivityPlugin)
public class BeachSessionActivityPlugin: CAPPlugin, CAPBridgedPlugin {
    public let identifier = "BeachSessionActivityPlugin"
    public let jsName = "BeachSessionActivity"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "start", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "update", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "end", returnType: CAPPluginReturnPromise),
        CAPPluginMethod(name: "getStatus", returnType: CAPPluginReturnPromise)
    ]

    /// Per-activity token/state-change observer tasks, keyed by ActivityKit's
    /// own activity id, so they can be cancelled when that activity ends and
    /// never leak across a start/end/start cycle.
    #if canImport(ActivityKit)
    @available(iOS 16.2, *)
    private static var observers: [String: [Task<Void, Never>]] = [:]
    #endif

    /// Phase 3 — the app's `bd:device-id` (and, optionally, its build
    /// number), the activity's `slug`, its install token (a secret — the
    /// server now requires it on /register and /end), and a monotonic
    /// rotation counter for token-rotation ordering. Kept alongside
    /// `observers` in memory, but Live Activities survive app termination
    /// while this static dictionary does not, so it is ALSO persisted to the
    /// Keychain (see `keychainSave`/`keychainLoad`/`keychainDelete` below)
    /// and restored in `load()` before observers reattach — otherwise a
    /// relaunch loses the device id and installToken and every rotation or
    /// dismissal after that silently fails to reach the server.
    private struct ActivityMeta: Codable {
        let deviceId: String
        let appBuild: String?
        let slug: String
        let installToken: String
        var rotation: Int
    }
    #if canImport(ActivityKit)
    @available(iOS 16.2, *)
    private static var activityMeta: [String: ActivityMeta] = [:]
    #endif

    // MARK: - Keychain persistence for activityMeta
    //
    // NOT UserDefaults: installToken is a secret. kSecClassGenericPassword,
    // service fixed, account = activityId (one entry per activity).
    // kSecAttrAccessibleAfterFirstUnlock so a token-rotation delivered while
    // the device is locked (but after first unlock this boot) can still be
    // read and uploaded.

    private static let keychainService = "com.isitbeachday.app.beachsession"

    private static func keychainQuery(id: String) -> [String: Any] {
        [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: keychainService,
            kSecAttrAccount as String: id
        ]
    }

    private static func keychainSave(id: String, meta: ActivityMeta) {
        guard let data = try? JSONEncoder().encode(meta) else { return }
        var query = keychainQuery(id: id)
        SecItemDelete(query as CFDictionary)
        query[kSecValueData as String] = data
        query[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlock
        SecItemAdd(query as CFDictionary, nil)
    }

    private static func keychainLoad(id: String) -> ActivityMeta? {
        var query = keychainQuery(id: id)
        query[kSecReturnData as String] = true
        query[kSecMatchLimit as String] = kSecMatchLimitOne
        var result: AnyObject?
        let status = SecItemCopyMatching(query as CFDictionary, &result)
        guard status == errSecSuccess, let data = result as? Data else { return nil }
        return try? JSONDecoder().decode(ActivityMeta.self, from: data)
    }

    private static func keychainDelete(id: String) {
        SecItemDelete(keychainQuery(id: id) as CFDictionary)
    }

    // MARK: - Origin restriction

    private static let allowedHost = "app.isitbeachday.com"

    private func originAllowed() -> Bool {
        // No URL yet (very early launch) — fail closed, even in DEBUG: a
        // missing URL is never "trust it", only an explicit allowed
        // scheme+host is.
        guard let url = bridge?.webView?.url, let host = url.host, let scheme = url.scheme else {
            return false
        }
        if scheme == "https" && host == Self.allowedHost { return true }
        #if DEBUG
        if (scheme == "http" || scheme == "https") && (host == "localhost" || host == "127.0.0.1") { return true }
        #endif
        return false
    }

    // MARK: - Availability

    private func requireAvailable(_ call: CAPPluginCall) -> Bool {
        #if canImport(ActivityKit)
        if #available(iOS 16.2, *) {
            if !originAllowed() {
                call.resolve(["ok": false, "reason": "origin-not-allowed"])
                return false
            }
            if !ActivityAuthorizationInfo().areActivitiesEnabled {
                call.resolve(["ok": false, "reason": "activities-not-enabled"])
                return false
            }
            return true
        }
        #endif
        call.resolve(["ok": false, "reason": "unsupported-os-version"])
        return false
    }

    // MARK: - start

    @objc func start(_ call: CAPPluginCall) {
        guard requireAvailable(call) else { return }
        #if canImport(ActivityKit)
        if #available(iOS 16.2, *) {
            // Phase 3: the plugin uploads its own push token, so it needs the
            // app's device id even though the WebView JS was the one asking
            // it to start — a rotation can arrive while that JS is dead.
            guard let deviceId = call.getString("deviceId"), Self.isValidDeviceId(deviceId) else {
                call.resolve(["ok": false, "reason": "invalid-deviceId"])
                return
            }
            let appBuildRaw = call.getString("appBuild")
            let appBuild = (appBuildRaw?.isEmpty ?? true) ? nil : appBuildRaw

            // The server now requires an install token on /register and
            // /end (see uploadPushToken/uploadEnd) — never logged.
            guard let installToken = call.getString("installToken"), !installToken.isEmpty else {
                call.resolve(["ok": false, "reason": "invalid-installToken"])
                return
            }

            guard let attributesObj = call.getObject("attributes") else {
                call.resolve(["ok": false, "reason": "invalid-attributes"])
                return
            }
            guard let attributes = Self.parseAttributes(attributesObj) else {
                call.resolve(["ok": false, "reason": "invalid-attributes"])
                return
            }
            guard let stateObj = call.getObject("state") else {
                call.resolve(["ok": false, "reason": "invalid-state"])
                return
            }
            guard let content = Self.parseContentState(stateObj) else {
                call.resolve(["ok": false, "reason": "invalid-state"])
                return
            }

            Task {
                // One active session per device: end every existing
                // BeachSession activity first, same rule BeachSessionDemo
                // follows for its own relaunches.
                for existing in Activity<BeachSessionAttributes>.activities {
                    Self.cancelObservers(for: existing.id)
                    await existing.end(existing.content, dismissalPolicy: .immediate)
                }

                let staleDate = content.state.updatedAt.addingTimeInterval(20 * 60)
                let activityContent = ActivityContent(state: content.state, staleDate: staleDate)
                do {
                    let activity = try Activity.request(
                        attributes: attributes,
                        content: activityContent,
                        pushType: .token
                    )
                    let meta = ActivityMeta(deviceId: deviceId, appBuild: appBuild, slug: attributes.slug, installToken: installToken, rotation: 0)
                    Self.activityMeta[activity.id] = meta
                    Self.keychainSave(id: activity.id, meta: meta)
                    Self.attachObservers(to: activity, plugin: self)
                    call.resolve(["ok": true, "activityId": activity.id])
                } catch {
                    call.resolve(["ok": false, "reason": "start-failed: \(error.localizedDescription)"])
                }
            }
            return
        }
        #endif
        call.resolve(["ok": false, "reason": "unsupported-os-version"])
    }

    // MARK: - update

    @objc func update(_ call: CAPPluginCall) {
        guard requireAvailable(call) else { return }
        #if canImport(ActivityKit)
        if #available(iOS 16.2, *) {
            guard let activityId = call.getString("activityId"), !activityId.isEmpty else {
                call.resolve(["ok": false, "reason": "invalid-activityId"])
                return
            }
            guard let stateObj = call.getObject("state") else {
                call.resolve(["ok": false, "reason": "invalid-state"])
                return
            }
            guard let content = Self.parseContentState(stateObj) else {
                call.resolve(["ok": false, "reason": "invalid-state"])
                return
            }
            guard let activity = Activity<BeachSessionAttributes>.activities.first(where: { $0.id == activityId }) else {
                call.resolve(["ok": false, "reason": "activity-not-found"])
                return
            }
            Task {
                let staleDate = content.state.updatedAt.addingTimeInterval(20 * 60)
                let activityContent = ActivityContent(state: content.state, staleDate: staleDate)
                await activity.update(activityContent)
                call.resolve(["ok": true])
            }
            return
        }
        #endif
        call.resolve(["ok": false, "reason": "unsupported-os-version"])
    }

    // MARK: - end

    @objc func end(_ call: CAPPluginCall) {
        guard requireAvailable(call) else { return }
        #if canImport(ActivityKit)
        if #available(iOS 16.2, *) {
            guard let activityId = call.getString("activityId"), !activityId.isEmpty else {
                call.resolve(["ok": false, "reason": "invalid-activityId"])
                return
            }
            let dismissalRaw = call.getString("dismissal") ?? "default"
            guard dismissalRaw == "immediate" || dismissalRaw == "default" else {
                call.resolve(["ok": false, "reason": "invalid-dismissal"])
                return
            }
            guard let activity = Activity<BeachSessionAttributes>.activities.first(where: { $0.id == activityId }) else {
                // Already gone (e.g. the OS ended it, or the user dismissed
                // it) — that's success from the caller's point of view.
                call.resolve(["ok": true])
                return
            }
            var finalContent: ActivityContent<BeachSessionAttributes.ContentState> = activity.content
            if let finalObj = call.getObject("finalState") {
                // Present but invalid must be a rejection, not a silent fall
                // back to the activity's last-known content — the caller
                // asked to end with specific final numbers and deserves to
                // know they didn't take.
                guard let parsed = Self.parseContentState(finalObj) else {
                    call.resolve(["ok": false, "reason": "invalid-final-state"])
                    return
                }
                finalContent = ActivityContent(state: parsed.state, staleDate: nil)
            }
            let policy: ActivityUIDismissalPolicy = dismissalRaw == "immediate" ? .immediate : .default
            Task {
                // User-initiated Off: report it before the metadata that
                // names the deviceId is torn down.
                Self.uploadEnd(activityId: activity.id)
                Self.cancelObservers(for: activity.id)
                await activity.end(finalContent, dismissalPolicy: policy)
                call.resolve(["ok": true])
            }
            return
        }
        #endif
        call.resolve(["ok": false, "reason": "unsupported-os-version"])
    }

    // MARK: - getStatus

    @objc func getStatus(_ call: CAPPluginCall) {
        #if canImport(ActivityKit)
        if #available(iOS 16.2, *) {
            guard originAllowed() else {
                call.resolve(["enabled": false, "activities": []])
                return
            }
            // A relaunch never re-runs start(), so this is the one place a
            // freshly-loaded WebView is guaranteed to pass through — (re)wire
            // observers to whatever survived, exactly once each.
            Self.reattachObservers(plugin: self)
            let enabled = ActivityAuthorizationInfo().areActivitiesEnabled
            let activities = Activity<BeachSessionAttributes>.activities.map { activity -> [String: Any] in
                ["id": activity.id, "state": Self.encodeContentState(activity.content.state)]
            }
            call.resolve(["enabled": enabled, "activities": activities])
            return
        }
        #endif
        call.resolve(["enabled": false, "activities": []])
    }

    // MARK: - Plugin lifecycle

    #if canImport(ActivityKit)
    public override func load() {
        if #available(iOS 16.2, *) {
            // Restore persisted metadata BEFORE attaching observers — a
            // relaunch's fresh process has an empty `activityMeta` even
            // though the Live Activity itself survived termination.
            // reattachObservers does the restore itself (see below), so
            // ordering is guaranteed for every call site, not just this one.
            Self.reattachObservers(plugin: self)
        }
    }
    #endif

    #if canImport(ActivityKit)
    // MARK: - Observers (token rotation + activity-state changes)

    @available(iOS 16.2, *)
    private static func attachObservers(to activity: Activity<BeachSessionAttributes>, plugin: BeachSessionActivityPlugin) {
        let id = activity.id
        let tokenTask = Task {
            for await tokenData in activity.pushTokenUpdates {
                // Never log the token itself — only its byte length, if that.
                let hex = tokenData.map { String(format: "%02x", $0) }.joined()
                plugin.notifyListeners(
                    "pushToken",
                    data: ["activityId": id, "token": hex],
                    retainUntilConsumed: true
                )
                // A rotation can arrive while the WebView JS is dead — the
                // plugin uploads it itself rather than relying on the card
                // to relay this event (Phase 3).
                Self.uploadPushToken(activityId: id, token: hex)
            }
        }
        let stateTask = Task {
            for await state in activity.activityStateUpdates {
                plugin.notifyListeners(
                    "activityState",
                    data: ["activityId": id, "state": Self.describeActivityState(state)],
                    retainUntilConsumed: true
                )
                if state == .dismissed {
                    // The user dismissed the Lock Screen card directly (not
                    // through the app's Off button) — report it the same way.
                    Self.uploadEnd(activityId: id)
                }
                if state == .dismissed || state == .ended {
                    Self.cancelObservers(for: id)
                    return
                }
            }
        }
        observers[id] = [tokenTask, stateTask]
    }

    @available(iOS 16.2, *)
    private static func cancelObservers(for id: String) {
        observers[id]?.forEach { $0.cancel() }
        observers[id] = nil
        activityMeta[id] = nil
        // Only reached once the activity is confirmed ended/dismissed (every
        // call site is inside an `end`/`.dismissed`/`.ended` path, or is
        // itself ending the activity right after) — safe to drop the
        // Keychain entry here.
        keychainDelete(id: id)
    }

    /// Loads any persisted metadata this process doesn't already have in
    /// memory for a currently-known activity. A relaunch starts with an
    /// empty `activityMeta` even though the Live Activity itself survived
    /// termination, so this MUST run before observers (re)attach — every
    /// caller of `reattachObservers` gets that ordering for free.
    @available(iOS 16.2, *)
    private static func restoreActivityMeta() {
        var restoredCount = 0
        for activity in Activity<BeachSessionAttributes>.activities where activityMeta[activity.id] == nil {
            if let meta = keychainLoad(id: activity.id) {
                activityMeta[activity.id] = meta
                restoredCount += 1
            }
        }
        if restoredCount > 0 {
            // Non-secret: count only, never the token/deviceId values.
            print("[LiveActivityPlugin] restored meta for \(restoredCount) activity\(restoredCount == 1 ? "" : "ies")")
        }
    }

    /// (Re)attach observers to every currently-known activity that doesn't
    /// already have one — idempotent, so calling this from both `load()` and
    /// `getStatus()` never double-subscribes an activity that survived a
    /// relaunch.
    @available(iOS 16.2, *)
    private static func reattachObservers(plugin: BeachSessionActivityPlugin) {
        restoreActivityMeta()
        for activity in Activity<BeachSessionAttributes>.activities where observers[activity.id] == nil {
            attachObservers(to: activity, plugin: plugin)
        }
    }

    @available(iOS 16.2, *)
    private static func describeActivityState(_ state: ActivityState) -> String {
        // `.pending` was added in iOS 26 — this function itself is only
        // gated at 16.2, so the case can't be named directly in the switch
        // below without breaking that lower deployment target. Test for it
        // by value, behind its own availability check, and let the switch's
        // `@unknown default` cover it (and any other future case) on OS
        // versions where it doesn't exist.
        if #available(iOS 26.0, *), state == .pending {
            return "pending"
        }
        switch state {
        case .active: return "active"
        case .dismissed: return "dismissed"
        case .ended: return "ended"
        case .stale: return "stale"
        @unknown default: return "unknown"
        }
    }

    // MARK: - Server upload (Phase 3)
    //
    // The plugin, not the WebView JS, owns telling the server about a push
    // token or an end — a rotation or a Lock Screen dismissal can arrive
    // while the JS is dead (backgrounded tab, killed WebView). Same origin
    // discipline as app/api/live-activity/*.ts: native-only via the
    // `IsItBeachDayApp/ios` User-Agent marker (lib/nativeRequest.ts), fixed
    // host so this can't be redirected by a compromised/rotated web origin.
    // Best-effort only — the server's own expiry sweep is the backstop for
    // a report that never lands (docs/LIVE_ACTIVITY_PLAN.md Phase 3).

    private static let uploadHost = "https://app.isitbeachday.com"
    private static let uploadUserAgent = "IsItBeachDayApp/ios"
    private static let uploadMaxAttempts = 3

    private static var isDebugBuild: Bool {
        #if DEBUG
        return true
        #else
        return false
        #endif
    }

    /// Mirrors lib/db/api.ts's `DEVICE_ID_RE` — same shape as the deviceId
    /// this plugin's JS caller reads from `bd:device-id`.
    private static let deviceIdPattern = try? NSRegularExpression(pattern: "^[A-Za-z0-9_:.-]{8,128}$")

    private static func isValidDeviceId(_ s: String) -> Bool {
        guard !s.isEmpty, s.count <= 128 else { return false }
        let range = NSRange(location: 0, length: s.utf16.count)
        return deviceIdPattern?.firstMatch(in: s, range: range) != nil
    }

    private static func postJSON(path: String, body: [String: Any], installToken: String, attemptsLeft: Int = uploadMaxAttempts) {
        guard let url = URL(string: uploadHost + path) else { return }
        guard let data = try? JSONSerialization.data(withJSONObject: body) else { return }
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue(uploadUserAgent, forHTTPHeaderField: "User-Agent")
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        // Never logged — the server-required install token, same secret
        // persisted alongside this activity's metadata.
        request.setValue(installToken, forHTTPHeaderField: "x-install-token")
        request.httpBody = data

        let task = URLSession.shared.dataTask(with: request) { _, response, error in
            if let http = response as? HTTPURLResponse {
                // Success, or a 4xx (bad request / not-armed / rate-limited /
                // unauthorized / forbidden): never retry a 4xx — the cron
                // sweep is the backstop, and retrying a rejection the server
                // already understood (including a bad/expired install
                // token — 401/403) would just be noise.
                if (200...299).contains(http.statusCode) { return }
                if (400...499).contains(http.statusCode) { return }
            }
            // Network error, no response, or a 5xx — worth a retry, if any
            // attempts remain.
            guard attemptsLeft > 1 else { return }
            let delay = Self.retryDelaySeconds(attemptsLeft: attemptsLeft)
            DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + delay) {
                Self.postJSON(path: path, body: body, installToken: installToken, attemptsLeft: attemptsLeft - 1)
            }
        }
        task.resume()
    }

    private static func retryDelaySeconds(attemptsLeft: Int) -> Double {
        switch attemptsLeft {
        case uploadMaxAttempts: return 1
        case uploadMaxAttempts - 1: return 3
        default: return 6
        }
    }

    @available(iOS 16.2, *)
    private static func uploadPushToken(activityId: String, token: String) {
        guard var meta = activityMeta[activityId] else { return }
        // Monotonic per-activity rotation counter, persisted alongside the
        // rest of the metadata, so the server can reject an out-of-order
        // retry of an earlier rotation.
        meta.rotation += 1
        activityMeta[activityId] = meta
        keychainSave(id: activityId, meta: meta)
        var body: [String: Any] = [
            "deviceId": meta.deviceId,
            "activityId": activityId,
            "slug": meta.slug,
            "pushToken": token,
            "schemaVersion": 1,
            "apnsEnvironment": isDebugBuild ? "sandbox" : "production",
            "rotation": meta.rotation,
        ]
        if let appBuild = meta.appBuild { body["appBuild"] = appBuild }
        postJSON(path: "/api/live-activity/register", body: body, installToken: meta.installToken)
    }

    @available(iOS 16.2, *)
    private static func uploadEnd(activityId: String) {
        guard let meta = activityMeta[activityId] else { return }
        postJSON(
            path: "/api/live-activity/end",
            body: ["deviceId": meta.deviceId, "activityId": activityId],
            installToken: meta.installToken
        )
    }

    // MARK: - Parsing + validation

    private static let slugPattern = try? NSRegularExpression(pattern: "^[a-z0-9]+(-[a-z0-9]+)*$")

    private static func isValidSlug(_ s: String) -> Bool {
        guard !s.isEmpty, s.count <= 120 else { return false }
        let range = NSRange(location: 0, length: s.utf16.count)
        return slugPattern?.firstMatch(in: s, range: range) != nil
    }

    @available(iOS 16.2, *)
    private static func parseAttributes(_ obj: [String: Any]) -> BeachSessionAttributes? {
        guard let beachName = obj["beachName"] as? String, !beachName.isEmpty, beachName.count <= 200 else { return nil }
        guard let slug = obj["slug"] as? String, isValidSlug(slug) else { return nil }
        guard let sessionStart = epochMs(obj["sessionStart"]) else { return nil }
        return BeachSessionAttributes(beachName: beachName, slug: slug, sessionStart: sessionStart)
    }

    /// A validated ContentState plus a typed accessor to its `updatedAt`
    /// (used to compute the stale date) without re-parsing.
    @available(iOS 16.2, *)
    private struct ParsedContent {
        let state: BeachSessionAttributes.ContentState
    }

    /// Swift bridges a JS boolean to NSNumber, so `true`/`false` would
    /// otherwise pass `as? NSNumber` and read back as 1/0 — a malformed
    /// payload silently accepted as a number. Reject CFBoolean explicitly
    /// before any numeric validator trusts the cast.
    private static func isBoolean(_ n: NSNumber) -> Bool {
        CFGetTypeID(n as CFTypeRef) == CFBooleanGetTypeID()
    }

    private static func epochMs(_ v: Any?) -> Date? {
        guard let n = v as? NSNumber, !isBoolean(n) else { return nil }
        let ms = n.doubleValue
        guard ms.isFinite else { return nil }
        return Date(timeIntervalSince1970: ms / 1000)
    }

    private static func finiteDouble(_ v: Any?) -> Double? {
        guard let n = v as? NSNumber, !isBoolean(n) else { return nil }
        let d = n.doubleValue
        return d.isFinite ? d : nil
    }

    /// A finite, whole-number NSNumber (e.g. `83.6` for `score` is rejected,
    /// not silently truncated to 83 — a fractional score/seq/version is a
    /// malformed payload, not an honest one with extra precision).
    private static func finiteInt(_ v: Any?) -> Int? {
        guard let d = finiteDouble(v),
              d.truncatingRemainder(dividingBy: 1) == 0,
              d >= Double(Int.min), d <= Double(Int.max) else { return nil }
        return Int(d)
    }

    private static func nonNegativeDouble(_ v: Any?) -> Double? {
        guard let d = finiteDouble(v), d >= 0 else { return nil }
        return d
    }

    /// A compass bearing in degrees, 0...360 inclusive.
    private static func bearingDouble(_ v: Any?) -> Double? {
        guard let d = finiteDouble(v), d >= 0, d <= 360 else { return nil }
        return d
    }

    @available(iOS 16.2, *)
    private static func parseContentState(_ obj: [String: Any]) -> ParsedContent? {
        // v must be exactly the schema version this build understands (1).
        guard let v = finiteInt(obj["v"]), v == 1 else { return nil }
        guard let seq = finiteInt(obj["seq"]), seq >= 0 else { return nil }
        guard let score = finiteInt(obj["score"]), score >= 0, score <= 100 else { return nil }
        guard let updatedAt = epochMs(obj["updatedAt"]) else { return nil }

        // Every field below is OPTIONAL in the wire payload; a present-but-
        // malformed value is rejected outright (better an honest failure than
        // a silently wrong Lock Screen), but an absent one is simply nil.
        if obj["windMph"] != nil, nonNegativeDouble(obj["windMph"]) == nil { return nil }
        if obj["gustMph"] != nil, nonNegativeDouble(obj["gustMph"]) == nil { return nil }
        if obj["windDeg"] != nil, bearingDouble(obj["windDeg"]) == nil { return nil }
        if obj["waveFt"] != nil, nonNegativeDouble(obj["waveFt"]) == nil { return nil }
        // Exact enum strings only — an unrecognized code is malformed, not a
        // free-text label to pass through to the widget.
        if let clarity = obj["clarity"] {
            guard let s = clarity as? String, s == "clear" || s == "murky" else { return nil }
        }
        if let seaweed = obj["seaweed"] {
            guard let s = seaweed as? String, s == "low" || s == "moderate" || s == "high" else { return nil }
        }
        if obj["nextTideAt"] != nil, epochMs(obj["nextTideAt"]) == nil { return nil }
        if let kind = obj["nextTideKind"] {
            guard let s = kind as? String, s == "high" || s == "low" else { return nil }
        }
        if obj["sunsetAt"] != nil, epochMs(obj["sunsetAt"]) == nil { return nil }

        var lightning: BeachSessionAttributes.ContentState.Lightning?
        if let lightningObj = obj["lightning"] as? [String: Any] {
            guard let active = lightningObj["active"] as? Bool else { return nil }
            guard let latched = lightningObj["latched"] as? Bool else { return nil }
            if lightningObj["miles"] != nil, nonNegativeDouble(lightningObj["miles"]) == nil { return nil }
            if lightningObj["bearingDeg"] != nil, bearingDouble(lightningObj["bearingDeg"]) == nil { return nil }
            if lightningObj["observedAt"] != nil, epochMs(lightningObj["observedAt"]) == nil { return nil }
            if lightningObj["holdUntil"] != nil, epochMs(lightningObj["holdUntil"]) == nil { return nil }
            lightning = BeachSessionAttributes.ContentState.Lightning(
                active: active,
                latched: latched,
                miles: nonNegativeDouble(lightningObj["miles"]),
                bearingDeg: bearingDouble(lightningObj["bearingDeg"]),
                observedAt: epochMs(lightningObj["observedAt"]),
                holdUntil: epochMs(lightningObj["holdUntil"])
            )
        } else if obj["lightning"] != nil {
            return nil // present but not an object
        }

        if let unavailable = obj["unavailable"], !(unavailable is Bool) { return nil }
        if let ended = obj["ended"], !(ended is Bool) { return nil }

        let state = BeachSessionAttributes.ContentState(
            v: v,
            seq: seq,
            score: score,
            windMph: nonNegativeDouble(obj["windMph"]),
            gustMph: nonNegativeDouble(obj["gustMph"]),
            windDeg: bearingDouble(obj["windDeg"]),
            waveFt: nonNegativeDouble(obj["waveFt"]),
            clarity: obj["clarity"] as? String,
            seaweed: obj["seaweed"] as? String,
            nextTideAt: epochMs(obj["nextTideAt"]),
            nextTideKind: obj["nextTideKind"] as? String,
            sunsetAt: epochMs(obj["sunsetAt"]),
            lightning: lightning,
            updatedAt: updatedAt,
            unavailable: obj["unavailable"] as? Bool,
            ended: obj["ended"] as? Bool
        )
        return ParsedContent(state: state)
    }

    @available(iOS 16.2, *)
    private static func encodeContentState(_ state: BeachSessionAttributes.ContentState) -> [String: Any] {
        var out: [String: Any] = [
            "v": state.v,
            "seq": state.seq,
            "score": state.score,
            "updatedAt": state.updatedAt.timeIntervalSince1970 * 1000
        ]
        if let x = state.windMph { out["windMph"] = x }
        if let x = state.gustMph { out["gustMph"] = x }
        if let x = state.windDeg { out["windDeg"] = x }
        if let x = state.waveFt { out["waveFt"] = x }
        if let x = state.clarity { out["clarity"] = x }
        if let x = state.seaweed { out["seaweed"] = x }
        if let x = state.nextTideAt { out["nextTideAt"] = x.timeIntervalSince1970 * 1000 }
        if let x = state.nextTideKind { out["nextTideKind"] = x }
        if let x = state.sunsetAt { out["sunsetAt"] = x.timeIntervalSince1970 * 1000 }
        if let l = state.lightning {
            var lo: [String: Any] = ["active": l.active, "latched": l.latched]
            if let x = l.miles { lo["miles"] = x }
            if let x = l.bearingDeg { lo["bearingDeg"] = x }
            if let x = l.observedAt { lo["observedAt"] = x.timeIntervalSince1970 * 1000 }
            if let x = l.holdUntil { lo["holdUntil"] = x.timeIntervalSince1970 * 1000 }
            out["lightning"] = lo
        }
        if let x = state.unavailable { out["unavailable"] = x }
        if let x = state.ended { out["ended"] = x }
        return out
    }
    #endif

    // MARK: - DEBUG probe (verifies the code path without the WebView)
    //
    // Exercised by AppDelegate when launched with
    // `--probe-live-activity-plugin` — calls start/update/end through the
    // SAME static parse/encode helpers and Activity<> calls the bridge uses,
    // proving the plugin class is registered and this code path runs, without
    // needing a live WKWebView round-trip (which xcrun simctl can't drive).
    #if DEBUG
    static func runProbe() {
        #if canImport(ActivityKit)
        if #available(iOS 16.2, *) {
            guard ActivityAuthorizationInfo().areActivitiesEnabled else {
                print("[LiveActivityProbe] skipped: Live Activities not enabled")
                return
            }
            let nowMs = Date().timeIntervalSince1970 * 1000
            let attrsObj: [String: Any] = ["beachName": "Probe Beach", "slug": "probe-beach", "sessionStart": nowMs]
            let stateObj: [String: Any] = ["v": 1, "seq": 0, "score": 77, "updatedAt": nowMs]
            guard let attributes = parseAttributes(attrsObj), let content = parseContentState(stateObj) else {
                print("[LiveActivityProbe] FAILED: parse rejected known-good probe payloads")
                return
            }

            // Codable round-trip check: ActivityKit serializes ContentState
            // between the app and the widget extension (and on every local
            // update) through Codable, not just for an APNs push decode. A
            // mismatched encode(to:)/init(from:) pair would silently corrupt
            // every date field reaching the Lock Screen. Independent of the
            // Activity<> calls below, so it always runs.
            do {
                let sample = BeachSessionAttributes.ContentState(
                    v: 1, seq: 2, score: 50,
                    nextTideAt: Date(timeIntervalSince1970: 1_800_000_000.123),
                    sunsetAt: Date(timeIntervalSince1970: 1_800_050_000.456),
                    lightning: BeachSessionAttributes.ContentState.Lightning(
                        active: true, latched: false,
                        observedAt: Date(timeIntervalSince1970: 1_800_010_000.789),
                        holdUntil: Date(timeIntervalSince1970: 1_800_020_000.321)
                    ),
                    updatedAt: Date(timeIntervalSince1970: 1_800_030_000.654)
                )
                let data = try JSONEncoder().encode(sample)
                let decoded = try JSONDecoder().decode(BeachSessionAttributes.ContentState.self, from: data)
                let pairs: [(String, Date?, Date?)] = [
                    ("updatedAt", sample.updatedAt, decoded.updatedAt),
                    ("nextTideAt", sample.nextTideAt, decoded.nextTideAt),
                    ("sunsetAt", sample.sunsetAt, decoded.sunsetAt),
                    ("lightning.observedAt", sample.lightning?.observedAt, decoded.lightning?.observedAt),
                    ("lightning.holdUntil", sample.lightning?.holdUntil, decoded.lightning?.holdUntil),
                ]
                var allOK = true
                for (name, a, b) in pairs {
                    guard let a, let b else {
                        if (a != nil) != (b != nil) {
                            allOK = false
                            print("[LiveActivityProbe] round-trip FAILED: \(name) nil mismatch")
                        }
                        continue
                    }
                    let diffMs = abs(a.timeIntervalSince(b)) * 1000
                    if diffMs > 1 {
                        allOK = false
                        print("[LiveActivityProbe] round-trip FAILED: \(name) off by \(diffMs)ms")
                    }
                }
                print(allOK
                    ? "[LiveActivityProbe] round-trip OK — Codable dates preserved"
                    : "[LiveActivityProbe] round-trip FAILED — see above")
            } catch {
                print("[LiveActivityProbe] round-trip FAILED: \(error)")
            }

            Task {
                for existing in Activity<BeachSessionAttributes>.activities {
                    cancelObservers(for: existing.id)
                    await existing.end(existing.content, dismissalPolicy: .immediate)
                }
                do {
                    let activityContent = ActivityContent(state: content.state, staleDate: nil)
                    // pushType stays nil here, same as before Phase 3: a
                    // push-token activity needs the aps-environment
                    // entitlement actually applied, which an unsigned/ad-hoc
                    // probe build doesn't have, and that's not what this
                    // probe is for. The Phase 3 upload path is exercised
                    // directly below instead, with a dummy deviceId and a
                    // synthetic hex token standing in for a real rotation —
                    // the register/end POSTs it fires may 4xx or simply time
                    // out against a simulator with no reachable network
                    // route, and that must stay silent (postJSON never
                    // throws or blocks); it is not treated as a probe
                    // failure.
                    let activity = try Activity.request(attributes: attributes, content: activityContent, pushType: nil)
                    // Dummy install token — the /register and /end uploads
                    // below may 4xx (server doesn't know this token) or time
                    // out against a simulator with no reachable network
                    // route, and that must stay silent per postJSON's own
                    // 4xx/no-retry rule; it is not a probe failure.
                    let meta = ActivityMeta(deviceId: "probe-device-000000000000", appBuild: nil, slug: activity.attributes.slug, installToken: "probe-install-token-0000000000", rotation: 0)
                    activityMeta[activity.id] = meta
                    keychainSave(id: activity.id, meta: meta)
                    print("[LiveActivityProbe] start OK activityId=\(activity.id)")
                    uploadPushToken(activityId: activity.id, token: "00" + String(repeating: "ab", count: 31))
                    let updated = BeachSessionAttributes.ContentState(
                        v: 1, seq: 1, score: 80, updatedAt: Date()
                    )
                    await activity.update(ActivityContent(state: updated, staleDate: nil))
                    print("[LiveActivityProbe] update OK")
                    uploadEnd(activityId: activity.id)
                    await activity.end(ActivityContent(state: updated, staleDate: nil), dismissalPolicy: .immediate)
                    cancelObservers(for: activity.id) // clears memory + Keychain now that it's confirmed ended
                    print("[LiveActivityProbe] end OK — plugin code path verified")
                } catch {
                    print("[LiveActivityProbe] start FAILED: \(error)")
                }
            }
            return
        }
        #endif
        print("[LiveActivityProbe] skipped: iOS < 16.2 or ActivityKit unavailable")
    }

    /// Starts an activity and its Keychain-persisted metadata but does NOT
    /// end it — exercised by AppDelegate with `--probe-live-activity-start-only`
    /// so a SEPARATE later launch (plain, no probe args — `load()` runs on
    /// every launch as the Capacitor bridge comes up) can prove Keychain
    /// restore by logging "restored meta for 1 activity" from
    /// `restoreActivityMeta()` before observers reattach.
    static func runProbeStartOnly() {
        #if canImport(ActivityKit)
        if #available(iOS 16.2, *) {
            guard ActivityAuthorizationInfo().areActivitiesEnabled else {
                print("[LiveActivityProbe] skipped: Live Activities not enabled")
                return
            }
            let nowMs = Date().timeIntervalSince1970 * 1000
            let attrsObj: [String: Any] = ["beachName": "Probe Beach", "slug": "probe-beach", "sessionStart": nowMs]
            let stateObj: [String: Any] = ["v": 1, "seq": 0, "score": 77, "updatedAt": nowMs]
            guard let attributes = parseAttributes(attrsObj), let content = parseContentState(stateObj) else {
                print("[LiveActivityProbe] FAILED: parse rejected known-good probe payloads")
                return
            }
            Task {
                for existing in Activity<BeachSessionAttributes>.activities {
                    cancelObservers(for: existing.id)
                    await existing.end(existing.content, dismissalPolicy: .immediate)
                }
                do {
                    let activityContent = ActivityContent(state: content.state, staleDate: nil)
                    let activity = try Activity.request(attributes: attributes, content: activityContent, pushType: nil)
                    let meta = ActivityMeta(deviceId: "probe-device-000000000000", appBuild: nil, slug: activity.attributes.slug, installToken: "probe-install-token-0000000000", rotation: 0)
                    activityMeta[activity.id] = meta
                    keychainSave(id: activity.id, meta: meta)
                    print("[LiveActivityProbe] start-only OK activityId=\(activity.id) — left running for a persistence check on next launch")
                } catch {
                    print("[LiveActivityProbe] start-only FAILED: \(error)")
                }
            }
            return
        }
        #endif
        print("[LiveActivityProbe] skipped: iOS < 16.2 or ActivityKit unavailable")
    }
    #endif
}
